---
# tasks file for k8s_master

  - name : Initialize the cluster
    shell : "kubeadm init --pod-network-cidr={{pod_ip_cidr}} --ignore-preflight-errors=NumCPU,Mem >> init.txt"
    args :
      chdir : $HOME
      creates : init.txt


  - name : Create Kube Directory
    file :
      path : $HOME/.kube
      state : directory
      owner : root
      mode : 640
  - name : Copy admin.conf
    copy:
        src: /etc/kubernetes/admin.conf
        dest: $HOME/.kube/config
        remote_src: yes
        owner: root
  - name : Download Overlay Network File
    template :
      src : kube-flannel.yml.jinja
      dest : $HOME/kube-flannel.yml

  - name: Setup Overlay network
    shell: kubectl apply -f kube-flannel.yml >> overlay_network_setup.txt
    args:
      chdir: $HOME
      creates: overlay_network_setup.txt

  - name: get join command
    shell: kubeadm token create --print-join-command
    register: join_command
    changed_when : false

  - name: set fact join command
    set_fact:
      join_command: "{{ join_command.stdout_lines[0] }}"

  - name : Printing Hostvars test
    debug :
      msg : "{{ hostvars[groups['tag_Name_Master_k8s'][0]].join_command }}"
